### ISSUE TITLE
AttributeError: module 'cleverbot' has no attribute 'Cleverbot'

### ISSUE THREAD

**Issue by MattBSG** [orlnub123/cleverbot.py#1]
Installed cleverbot.py through pip today and when defining variable cb, I get an Attribute error.

    import cleverbot
    cb = cleverbot.Cleverbot('TOKEN', timeout=15)

This was being used for a discord bot. The stacktrace is as follows:
    Traceback (most recent call last):
      File "cleverbot.py", line 5, in <module>
        import cleverbot
      File "/root/cleverbot/cleverbot.py", line 9, in <module>
        cb = cleverbot.Cleverbot('REDACTED', timeout=15)
    AttributeError: module 'cleverbot' has no attribute 'Cleverbot'

**Comment by orlnub123** [comment]
When importing Python first searches for the module in the current directory, which it found as your module's name is cleverbot. So instead of importing the cleverbot in site-packages it imported itself.

Changing your module's name will fix it.
